# Generated by Django 2.1.3 on 2019-02-18 18:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('prfs', '0004_auto_20190211_2331'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='prf',
            options={'permissions': (('custom permission', 'about custom permission'),), 'verbose_name': 'Профиль', 'verbose_name_plural': 'Профили'},
        ),
    ]
