# Generated by Django 2.1.3 on 2019-02-18 18:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('prfs', '0005_auto_20190218_2134'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='prf',
            options={'permissions': (('dashboard', 'view_dashboard'),), 'verbose_name': 'Профиль', 'verbose_name_plural': 'Профили'},
        ),
    ]
