# Generated by Django 2.1.3 on 2019-02-18 18:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('prfs', '0006_auto_20190218_2136'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='prf',
            options={'verbose_name': 'Профиль', 'verbose_name_plural': 'Профили'},
        ),
    ]
