# Generated by Django 2.1.3 on 2019-02-16 09:46

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0005_auto_20190125_1452'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comments',
            options={'verbose_name': ('комментарий',), 'verbose_name_plural': 'комментарии'},
        ),
        migrations.AlterField(
            model_name='comments',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2019, 2, 16, 9, 46, 53, 43378, tzinfo=utc)),
        ),
    ]
