# Generated by Django 2.1.3 on 2019-02-18 18:34

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0006_auto_20190216_1246'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2019, 2, 18, 18, 34, 6, 595072, tzinfo=utc)),
        ),
    ]
