# Generated by Django 2.1.3 on 2019-02-19 18:28

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0010_auto_20190218_2146'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2019, 2, 19, 18, 28, 27, 788861, tzinfo=utc)),
        ),
    ]
