# Generated by Django 2.1.3 on 2019-02-19 18:31

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0011_auto_20190219_2128'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2019, 2, 19, 18, 31, 13, 22426, tzinfo=utc)),
        ),
    ]
