# Generated by Django 2.1.3 on 2019-03-21 18:30

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0012_auto_20190219_2131'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2019, 3, 21, 18, 30, 27, 480467, tzinfo=utc)),
        ),
    ]
