# Generated by Django 2.1.3 on 2019-03-22 10:34

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0013_auto_20190321_2130'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2019, 3, 22, 10, 34, 18, 868407, tzinfo=utc)),
        ),
    ]
