# Generated by Django 2.1.3 on 2019-02-18 18:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0036_auto_20190216_1246'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='created',
            field=models.DateField(blank=True, default=datetime.date(2019, 2, 18), null=True, verbose_name='дата внесения в каталог'),
        ),
    ]
