# Generated by Django 2.1.3 on 2019-02-19 18:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0037_auto_20190218_2134'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='created',
            field=models.DateField(blank=True, default=datetime.date(2019, 2, 19), null=True, verbose_name='дата внесения в каталог'),
        ),
    ]
