# Generated by Django 2.1.3 on 2019-03-21 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0039_auto_20190219_2131'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='created',
            field=models.DateField(auto_now_add=True, verbose_name='дата внесения в каталог'),
        ),
        migrations.AlterField(
            model_name='book',
            name='updated',
            field=models.DateField(auto_now=True, verbose_name='дата последнего изменения карточки'),
        ),
    ]
